### ISSUE TITLE
installing error:  UNMET PEER DEPENDENCY eslint@>=0.8.0  (though eslint@1.6.0 is installed )

### ISSUE THREAD

**Issue by roberto68** [dferber90/eslint-plugin-meteor#23]
so I want to install eslint-plugin-meteor, but npm throws this error. So I install latest eslint (everything globally !!!) but the output is still the same.

**Comment by dferber90** [comment]
Thanks for trying out ESLint-plugin-Meteor! 👏

I know the documentation is lacking right now. Installing everything globally is not the best way. Have you read through [this](https://github.com/dferber90/eslint-plugin-meteor/blob/master/docs/SETUP_METEOR_PROJECT.md)?

**Comment by dferber90** [comment]
Any update on this?

**Comment by roberto68** [comment]
installing locally it went fine

**Comment by roberto68** [comment]
but it isn't showing any errors, is it better to install eslint globally and meteor-plugin locally?

**Comment by dferber90** [comment]
> Is it better to install eslint globally and meteor-plugin locally? 

It's best to install both locally, because it locks their versions down in `package.json`.

> or do I've to copy .eslintrc to root of my project directory?

You need one `.eslintrc` at the root of your Meteor project or in a directory above.

>  it isn't showing any errors

All rules are turned off by default. You have to enable them manually.

---
I'm going to write an article about all of that soon. I'm also going to create an example-project that shows how to set up everything properly. Until then, the link posted above and the official ESLint-docs are your best choice to learn more about linting.
