### ISSUE TITLE
Rule Advancement: audit-argument-checks only on server-side

### ISSUE THREAD

**Issue by shoetten** [dferber90/eslint-plugin-meteor#259]
Hey!
Would it be possible to add a configuration option to the audit-argument-checks rule, to only enable it on the server-side?
Sometimes it doesn't make much sense to check everything in method stubs..

**Comment by dferber90** [comment]
ESLint doesn't know where the code is going to run (because it's not aware of how Meteor interprets folder structure) so this is not easy to do. ESLint-plugin-Meteor tried to work around this at first, but this got way too complex. And with the module system it's even harder. Some people use webpack in Meteor and then you can't possibly reason where the code is going to run.

Either add a separate `.eslintrc` file extending the root one which has that rule disabled, and put it into the folder, or use inline comments to disable the rule for code blocks or lines.

**Comment by shoetten** [comment]
That's too bad, but thanks for the advice!
